version: '3.8'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234

  app:
    container_name: app
    image: com-smv/start-my-venture:2.2.0
    ports:
      - "8080:8080"
    environment:
      - "POSTGRES_DB_SERVER_ADDRESS=db"
      - "POSTGRES_DB_SERVER_PORT=5432"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=1234"
    depends_on:
      - db
