spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_SERVER_ADDRESS:localhost}:${POSTGRES_DB_SERVER_PORT:5432}/
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1234}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
      show-sql: true
      format-sql: true
      type: info
      use-sql-comments: true
      properties:
        hibernate.use_sql_comments: true
        hibernate.format_sql: true

#springdoc:
#  show-actuator: true
#  paths-to-match: /**
#  packages-to-scan: com.

management:
  endpoint:
    health:
      show-details: ALWAYS
    endpoints:
      web:
        exposure:
          include: "*"

logging:
  level:
    org.springframework: INFO
    com.farukgenc.boilerplate.springboot: INFO

## FIXME : Customize JWT token and Swagger information for your application

jwt:
  secretKey: secret
  issuer: www.kkk.com
  expirationMinute: 100

swagger:
  contact-name: ...
  contact-mail: ...
  contact-url: https://...com
  app-name: Spring Boot Boilerplate Project
  app-description: "Spring Boot Boilerplate is a starter kit. This project includes : Spring Boot(2.7.4), Spring Data JPA, Spring Validation, Spring Security + JWT Token, PostgreSQL, Mapstruct, Lombok, Swagger"
  app-version: 2.0.0
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0

openai-service:
  api-key: ##########################
  gpt-model: gpt-3.5-turbo
  audio-model: whisper-1
  http-client:
    read-timeout: 3000
    connect-timeout: 3000
  urls:
    base-url: https://api.openai.com/v1
    chat-url: /chat/completions
    create-transcription-url: /audio/transcriptions